/* --------------------------------------------------------------------------------
 #
 #	4DPlugin-Mount.h
 #	source generated by 4D Plugin Wizard
 #	Project : Mount
 #	author : miyako
 #	2019/10/02
 #  
 # --------------------------------------------------------------------------------*/

#ifndef PLUGIN_MOUNT_H
#define PLUGIN_MOUNT_H

#include "4DPluginAPI.h"
#include <mutex>
#include "C_TEXT.h"
#include "json.h"

#include <DiskArbitration/DiskArbitration.h>

void listenerInit(void);
void listenerLoop(void);
void listenerLoopStart(void);
void listenerLoopFinish(void);
void listenerLoopExecute(void);
void listenerLoopExecuteMethod(void);

typedef PA_long32 process_number_t;
typedef PA_long32 process_stack_size_t;
typedef PA_long32 method_id_t;
typedef PA_Unichar* process_name_t;

#pragma mark -

void Mount_WATCH(PA_PluginParameters params);
void Unmount(PA_PluginParameters params);
void Mount(PA_PluginParameters params);

typedef enum {
    
    didMountNotificationEvent = 1,
    willUnmountNotificationEvent,
    didUnmountNotificationEvent,
    didRenameVolumeNotificationEvent
    
}mount_event_id_t;

@interface Listener : NSObject {
    
    NSNotificationCenter *_notificationCenter;
    
}

- (void)didMountNotification:(NSNotification *)notification;
- (void)willUnmountNotification:(NSNotification *)notification;
- (void)didUnmountNotification:(NSNotification *)notification;
- (void)didRenameVolumeNotification:(NSNotification *)notification;
- (void)call:(mount_event_id_t)event notification:(NSNotification *)notification;

@end

#endif /* PLUGIN_MOUNT_H */
